Add several new hackathons
leonoverweel/dutch-hackathons pull request #3
Opened 2017-05-03 18:18 UTC by jverbraeken

Found some more hackathons:

- Hackup 2020
- HUH?! Hogeschool Utrecht Hackathon
- Dutch Health Hackathon

2017-05-03 19:45 UTC, leonoverweel requested changes
Hi @jverbraeken! Thanks for the additions - can you make this small fix? Then I'll merge.

2017-05-03 19:45 UTC, leonoverweel commented on README.md
> +| [Dutch Health Hackathon](http://www.dhh2017.nl/) | Leeuwarden | | 2017 (December 9 - 11) |
Can you add 2015 as a past edition here?

2017-05-03 21:01 UTC, jverbraeken commented on README.md
> +| [Dutch Health Hackathon](http://www.dhh2017.nl/) | Leeuwarden | | 2017 (December 9 - 11) |
@leonoverweel Done!

2017-05-04 10:25 UTC, leonoverweel approved these changes

2017-05-04 10:25 UTC, merged